version: '3'

services:
  api-node:
    build: .
    container_name: api-node
    ports:
      - "3000:3000" # Mapeia a porta do container para a máquina host
    networks:
      - minha-rede

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    networks:
      - minha-rede
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/

networks:
  minha-rede:
